name: Run npm script to update README menu

on:
  push:
    branches: vitepress
  
permissions: write-all

jobs:
  update-readme-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run npm script
        run: npm run md

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "docs(action): Update README.md"
            git pull
            git push https://open17@github.com/open17/alg-note.git HEAD:vitepress
          fi
